name: CI
push:
jobs:
  build:
    name: Build & test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
        
        # Install & build & test:
      - run: npm test
      - run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build